#!/usr/bin/env python3.10
from coordinates import get_coordinates
from exceptions import CantGetCoordinates, ApiServiceError
from weather_api_service import get_weather
from weather_formatter import format_weather


def main():
    try:
        coordinates = get_coordinates()
    except CantGetCoordinates:
        print("Couldn't get coordinates")
        exit(1)
    try:
        weather = get_weather(coordinates)
    except ApiServiceError:
        print(f"Couldn't get weather by coordinates {coordinates}")
    print(format_weather(weather))


if __name__ == '__main__':
    main()
